version: '3.5'

networks:
  dss-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
# To build custom dataiku_dss image, see docker-compose-build.yml file
#  dss:
#    build:
#      context: dss
#    image: dataiku_dss:${DSS_VERSION:-latest}
#

  design:
    image: dataiku_dss:${DSS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_dss_design
    networks:
      - dss-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DESIGN_DATADIR:-./data-design}:/home/dataiku/dss
      # add custom license
      #- ./license.json:/home/dataiku/license.json
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy},dkumonitor
      # add custom license, change install_size
      - DSS_INSTALLER_ARGS=${DESIGN_DSS_INSTALLER_ARGS:- -t design -s auto}
    ports:
      - ${DESIGN_PORT:-10000}:10000

  automation:
    image: dataiku_dss:${DSS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_dss_automation
    networks:
      - dss-network
    volumes:
      - ${AUTOMATION_DATADIR:-./data-automation}:/home/dataiku/dss
      # add custom license
      #- ./license.json:/home/dataiku/license.json
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy},dkumonitor
      # add custom license, change install_size
      - DSS_INSTALLER_ARGS=${AUTOMATION_DSS_INSTALLER_ARGS:- -t automation -s auto}
    ports:
      - ${AUTOMATION_PORT:-10001}:10000

  apideployer:
    image: dataiku_dss:${DSS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_dss_apideployer
    networks:
      - dss-network
    volumes:
      - ${APIDEPLOYER_DATADIR:-./data-apideployer}:/home/dataiku/dss
      # add custom license
      # - ./license.json:/home/dataiku/license.json
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy},dkumonitor
      # add custom license, change install_size
      - DSS_INSTALLER_ARGS=${APIDEPLOYER_DSS_INSTALLER_ARGS:- -t apideployer -s auto}
    ports:
      - ${APIDEPLOYER_PORT:-10002}:10000

  api:
    image: dataiku_dss:${DSS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_dss_api
    networks:
      - dss-network
    volumes:
      - ${API_DATADIR:-./data-api}:/home/dataiku/dss
      # add custom license
      #- ./license.json:/home/dataiku/license.json
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy},dkumonitor
      # add custom license, change install_size
      - DSS_INSTALLER_ARGS=${API_DSS_INSTALLER_ARGS:- -t api -s auto}
    ports:
      - ${API_PORT:-10003}:10000

  dkumonitor:
    image: dataiku_dkumonitor:${DKUMONITOR_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_dkumonitor
    networks:
      - dss-network
    volumes:
      - ${DKUMONITOR_DATADIR:-./data-dkumonitor}:/home/dkumonitor/data
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    ports:
      - "27600-27609:27600-27609"
