version: '3.5'
services:
  dss:
    build:
      context: dss
      dockerfile: Dockerfile
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - no_proxy=$no_proxy
        - DSS_VERSION
        - VERTICA_VERSION
        - MYSQL_VERSION
    image: dataiku_dss:${DSS_VERSION:-latest}
  dss_debian:
    build:
      context: dss
      dockerfile: Dockerfile.debian
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - no_proxy=$no_proxy
        - MIRROR_DEBIAN
        - MIRROR_DOCKER
        - MIRROR_DOCKER_KEY
        - DSS_VERSION
        - VERTICA_VERSION
        - MYSQL_VERSION
    image: dataiku_dss:${DSS_VERSION:-latest}
  dkumonitor:
    build:
      context: dkumonitor
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - no_proxy=$no_proxy
        - MIRROR_DEBIAN
        - DKUMONITOR_VERSION
    image: dataiku_dkumonitor:${DKUMONITOR_VERSION:-latest}
