version: '3.5'

networks:
  dss-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-12.6}
    container_name: ${COMPOSE_PROJECT_NAME}_db_postgres
    networks:
      - dss-network
    volumes:
      - ${POSTGRES_DATADIR:-./data-db-postgres}:/data/postgres
      - ./postgres-init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - PGDATA=/data/postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DATABASE_DSS=${POSTGRES_DATABASE_DSS:-dss}
      - POSTGRES_USER_DSS=${POSTGRES_USER_DSS:-dssuser}
      - POSTGRES_PASSWORD_DSS=${POSTGRES_PASSWORD_DSS:-dsschangeme}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
